name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get commit count
      id: get_commit_count
      run: echo "::set-output name=commit_count::$(git rev-list --count HEAD)"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: app/Dockerfile
        push: true
        build-args: |
          GITHUB_RUN_NUMBER=${{ github.run_number }}
          GITHUB_COMMIT_COUNT=${{ steps.get_commit_count.outputs.commit_count }}
        tags: ${{ secrets.DOCKER_USERNAME }}/flaskapp:${{ github.run_number }}
