name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install flake8
      run: pip install flake8

    - name: Run code linting
      run: |
        flake8 app/app.py
        echo "Running tests..."

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get commit count
      id: get_commit_count
      run: echo "::set-output name=commit_count::$(git rev-list --count HEAD)"

    - name: Build Docker image
      run: |
        docker build -t flaskapp:${{ github.run_number }} .
        docker tag flaskapp:${{ github.run_number }} registry.heroku.com/${{ secrets.TF_VAR_HEROKU_APP_NAME }}/web

    - name: Push Docker image to Heroku
      run: |
        docker push registry.heroku.com/${{ secrets.TF_VAR_HEROKU_APP_NAME }}/web

    - name: Deploy to Heroku
      run: |
        heroku container:release web --app ${{ secrets.TF_VAR_HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.TF_VAR_HEROKU_API_KEY }}
