name: Terraform Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_heroku_api_key: ${{ secrets.TF_VAR_heroku_api_key }}
      TF_VAR_heroku_email: ${{ secrets.TF_VAR_heroku_email }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Validate Terraform configuration
        run: terraform validate
        working-directory: terraform

      - name: Plan Terraform changes
        id: plan
        run: terraform plan -out=tfplan
        working-directory: terraform

      - name: Apply Terraform changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: terraform
