name: Terraform Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_heroku_api_key: ${{ secrets.TF_VAR_heroku_api_key }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Validate Terraform configuration
        working-directory: terraform
        run: terraform validate

      - name: Plan Terraform changes
        id: plan
        working-directory: terraform
        run: terraform plan -out=tfplan

      - name: Apply Terraform changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: terraform
        run: terraform apply -auto-approve tfplan
